name = "asset-plan"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Bind a D1 database. D1 is Cloudflare's native serverless SQL database.
# Docs: https://developers.cloudflare.cloudflare.com/d1/get-started/
[[d1_databases]]
binding = "DB"
database_name = "asset-plan-db"
database_id = "f40d3de1-ccdf-496e-9318-be957c8eecb8"
migrations_dir = "./db_migrations"
[[kv_namespaces]]
binding = "CACHE_KV"
id = "a70d8c7537a94f528076035d9059290b"
